plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "bin/**/*"

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Metrics/CyclomaticComplexity:
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Metrics/MethodLength:
  Exclude:
    - "spec/**/*"
    - "test/**/*"

RSpec/MultipleExpectations:
  Max: 2